// Configure via your venue API — see HEAT_INDEX in client/src/lib/heat-index-config.ts. Real published
// data, not fabricated. Republishes monthly — re-extract to refresh.
export const HEAT_INDEX = {
  "tierMult": {
    "S": 4.0,
    "A": 2.5,
    "B": 1.5,
    "C": 1.0
  },
  "volumePeak": 1.6,
  "streakMax": 1.3,
  "streakMaxWeeks": 8,
  "powerHour": 1.2,
  "matrix": {
    "USD/CAD": "C",
    "USD/MXN": "C",
    "USD/EUR": "C",
    "USD/GBP": "C",
    "USD/CHF": "C",
    "USD/TRY": "C",
    "USD/JPY": "C",
    "USD/SGD": "C",
    "USD/MYR": "C",
    "USD/IDR": "C",
    "USD/AED": "C",
    "USD/AUD": "C",
    "USD/NZD": "C",
    "USD/BRL": "C",
    "USD/ARS": "C",
    "USD/CLP": "C",
    "USD/COP": "C",
    "USD/PEN": "C",
    "USD/NGN": "C",
    "USD/ZAR": "C",
    "CAD/MXN": "A",
    "CAD/EUR": "B",
    "CAD/GBP": "B",
    "CAD/CHF": "B",
    "CAD/TRY": "A",
    "CAD/JPY": "B",
    "CAD/SGD": "A",
    "CAD/MYR": "A",
    "CAD/IDR": "A",
    "CAD/AED": "A",
    "CAD/AUD": "B",
    "CAD/NZD": "B",
    "CAD/BRL": "A",
    "CAD/ARS": "A",
    "CAD/CLP": "A",
    "CAD/COP": "A",
    "CAD/PEN": "A",
    "CAD/NGN": "A",
    "CAD/ZAR": "A",
    "MXN/EUR": "A",
    "MXN/GBP": "A",
    "MXN/CHF": "A",
    "MXN/TRY": "S",
    "MXN/JPY": "A",
    "MXN/SGD": "S",
    "MXN/MYR": "S",
    "MXN/IDR": "S",
    "MXN/AED": "S",
    "MXN/AUD": "A",
    "MXN/NZD": "A",
    "MXN/BRL": "S",
    "MXN/ARS": "S",
    "MXN/CLP": "S",
    "MXN/COP": "S",
    "MXN/PEN": "S",
    "MXN/NGN": "S",
    "MXN/ZAR": "S",
    "EUR/GBP": "B",
    "EUR/CHF": "B",
    "EUR/TRY": "A",
    "EUR/JPY": "B",
    "EUR/SGD": "A",
    "EUR/MYR": "A",
    "EUR/IDR": "A",
    "EUR/AED": "A",
    "EUR/AUD": "B",
    "EUR/NZD": "B",
    "EUR/BRL": "A",
    "EUR/ARS": "A",
    "EUR/CLP": "A",
    "EUR/COP": "A",
    "EUR/PEN": "A",
    "EUR/NGN": "A",
    "EUR/ZAR": "A",
    "GBP/CHF": "B",
    "GBP/TRY": "A",
    "GBP/JPY": "B",
    "GBP/SGD": "A",
    "GBP/MYR": "A",
    "GBP/IDR": "A",
    "GBP/AED": "A",
    "GBP/AUD": "B",
    "GBP/NZD": "B",
    "GBP/BRL": "A",
    "GBP/ARS": "A",
    "GBP/CLP": "A",
    "GBP/COP": "A",
    "GBP/PEN": "A",
    "GBP/NGN": "A",
    "GBP/ZAR": "A",
    "CHF/TRY": "A",
    "CHF/JPY": "B",
    "CHF/SGD": "A",
    "CHF/MYR": "A",
    "CHF/IDR": "A",
    "CHF/AED": "A",
    "CHF/AUD": "B",
    "CHF/NZD": "B",
    "CHF/BRL": "A",
    "CHF/ARS": "A",
    "CHF/CLP": "A",
    "CHF/COP": "A",
    "CHF/PEN": "A",
    "CHF/NGN": "A",
    "CHF/ZAR": "A",
    "TRY/JPY": "A",
    "TRY/SGD": "S",
    "TRY/MYR": "S",
    "TRY/IDR": "S",
    "TRY/AED": "S",
    "TRY/AUD": "A",
    "TRY/NZD": "A",
    "TRY/BRL": "S",
    "TRY/ARS": "S",
    "TRY/CLP": "S",
    "TRY/COP": "S",
    "TRY/PEN": "S",
    "TRY/NGN": "S",
    "TRY/ZAR": "S",
    "JPY/SGD": "A",
    "JPY/MYR": "A",
    "JPY/IDR": "A",
    "JPY/AED": "A",
    "JPY/AUD": "B",
    "JPY/NZD": "B",
    "JPY/BRL": "A",
    "JPY/ARS": "A",
    "JPY/CLP": "A",
    "JPY/COP": "A",
    "JPY/PEN": "A",
    "JPY/NGN": "A",
    "JPY/ZAR": "A",
    "SGD/MYR": "A",
    "SGD/IDR": "A",
    "SGD/AED": "S",
    "SGD/AUD": "A",
    "SGD/NZD": "A",
    "SGD/BRL": "S",
    "SGD/ARS": "S",
    "SGD/CLP": "S",
    "SGD/COP": "S",
    "SGD/PEN": "S",
    "SGD/NGN": "S",
    "SGD/ZAR": "S",
    "MYR/IDR": "A",
    "MYR/AED": "S",
    "MYR/AUD": "A",
    "MYR/NZD": "A",
    "MYR/BRL": "S",
    "MYR/ARS": "S",
    "MYR/CLP": "S",
    "MYR/COP": "S",
    "MYR/PEN": "S",
    "MYR/NGN": "S",
    "MYR/ZAR": "S",
    "IDR/AED": "S",
    "IDR/AUD": "A",
    "IDR/NZD": "A",
    "IDR/BRL": "S",
    "IDR/ARS": "S",
    "IDR/CLP": "S",
    "IDR/COP": "S",
    "IDR/PEN": "S",
    "IDR/NGN": "S",
    "IDR/ZAR": "S",
    "AED/AUD": "A",
    "AED/NZD": "A",
    "AED/BRL": "S",
    "AED/ARS": "S",
    "AED/CLP": "S",
    "AED/COP": "S",
    "AED/PEN": "S",
    "AED/NGN": "S",
    "AED/ZAR": "S",
    "AUD/NZD": "B",
    "AUD/BRL": "A",
    "AUD/ARS": "A",
    "AUD/CLP": "A",
    "AUD/COP": "A",
    "AUD/PEN": "A",
    "AUD/NGN": "A",
    "AUD/ZAR": "A",
    "NZD/BRL": "A",
    "NZD/ARS": "A",
    "NZD/CLP": "A",
    "NZD/COP": "A",
    "NZD/PEN": "A",
    "NZD/NGN": "A",
    "NZD/ZAR": "A",
    "BRL/ARS": "S",
    "BRL/CLP": "S",
    "BRL/COP": "S",
    "BRL/PEN": "S",
    "BRL/NGN": "S",
    "BRL/ZAR": "S",
    "ARS/CLP": "S",
    "ARS/COP": "S",
    "ARS/PEN": "S",
    "ARS/NGN": "S",
    "ARS/ZAR": "S",
    "CLP/COP": "S",
    "CLP/PEN": "S",
    "CLP/NGN": "S",
    "CLP/ZAR": "S",
    "COP/PEN": "S",
    "COP/NGN": "S",
    "COP/ZAR": "S",
    "PEN/NGN": "S",
    "PEN/ZAR": "S",
    "NGN/ZAR": "S"
  },
  "sessions": [
    {
      "id": "sydney",
      "name": "Sydney",
      "start_utc": "22:00",
      "end_utc": "06:00",
      "currencies": [
        "AUD",
        "NZD"
      ]
    },
    {
      "id": "tokyo",
      "name": "Tokyo",
      "start_utc": "23:00",
      "end_utc": "08:00",
      "currencies": [
        "JPY"
      ]
    },
    {
      "id": "singapore",
      "name": "Singapore",
      "start_utc": "00:00",
      "end_utc": "09:00",
      "currencies": [
        "SGD",
        "MYR",
        "IDR"
      ]
    },
    {
      "id": "dubai",
      "name": "Dubai",
      "start_utc": "04:00",
      "end_utc": "13:00",
      "currencies": [
        "AED"
      ]
    },
    {
      "id": "africa",
      "name": "Africa",
      "start_utc": "06:00",
      "end_utc": "15:00",
      "currencies": [
        "ZAR",
        "NGN"
      ]
    },
    {
      "id": "london",
      "name": "London",
      "start_utc": "07:00",
      "end_utc": "16:00",
      "currencies": [
        "EUR",
        "GBP",
        "CHF",
        "TRY"
      ]
    },
    {
      "id": "latam",
      "name": "LatAM",
      "start_utc": "12:00",
      "end_utc": "21:00",
      "currencies": [
        "BRL",
        "ARS",
        "CLP",
        "COP",
        "PEN",
        "MXN"
      ]
    }
  ]
};
