/**
 * ─── Wallet DEX Router ────────────────────────────────────────────────────────────
 *
 * Manages custodial wallets for each user.
 * Uses real secp256k1 keypairs generated by ethers.js Wallet.createRandom().
 * Private keys are stored AES-256-GCM encrypted in the wallet_keys table.
 */

import { z } from "zod";
import { eq } from "drizzle-orm";
import { Wallet } from "ethers";
import { TRPCError } from "@trpc/server";
import { getDb } from "../db";
import { protectedProcedure, router } from "../_core/trpc";
import { walletKeys, users, managedWalletCaps } from "../../drizzle/schema";
import { ENV } from "../_core/env";
import { fundTestnetWallet } from "../lib/dex/fundTestnetWallet";
import {
  generateRealWallet,
  encryptPrivateKey,
  isValidEthAddress,
} from "../lib/crypto";
import { getDexClient } from "../lib/dex/client";
import { assertRateLimit } from "../lib/production";

export const walletRouter = router({
  /**
   * Returns the user's app wallet, auto-creating one on first call.
   *
   * Priority order:
   *   1. Existing walletKeys row (auto-generated app wallet)
   *   2. users.walletAddress (imported external wallet)
   *   3. Auto-generate a new DEMO wallet and persist it
   */
  getOrCreate: protectedProcedure.query(async ({ ctx }) => {
    const db = await getDb();
    if (!db) return null;

    const userId = ctx.user.id;

    // 1. Check for existing auto-generated wallet
    const existing = await db
      .select({ address: walletKeys.address, createdAt: walletKeys.createdAt, imported: walletKeys.imported })
      .from(walletKeys)
      .where(eq(walletKeys.userId, userId))
      .limit(1);

    // Only an IMPORTED wallet counts as the user's active wallet. A legacy
    // auto-generated row (imported=false, left over from the now-removed
    // auto-create path) is a useless blank wallet — ignore it so the UI shows
    // "Import your wallet" instead of a confusing "Auto-generated / ACTIVE" card.
    // (Josh: do NOT generate or surface an app-made wallet.)
    if (existing[0] && existing[0].imported === true) {
      return {
        address: existing[0].address,
        createdAt: existing[0].createdAt,
        isImported: true,
      };
    }

    // 2. Check for imported wallet stored on the user row
    const userRow = await db
      .select({ walletAddress: users.walletAddress })
      .from(users)
      .where(eq(users.id, userId))
      .limit(1);

    if (userRow[0]?.walletAddress) {
      return {
        address: userRow[0].walletAddress,
        createdAt: null,
        isImported: true,
      };
    }

    // 3. Auto-generate — DISABLED (Josh): a blank app-generated wallet is
    // useless/confusing; testers must import their OWN funded testnet wallet.
    // Returning null → the UI shows the "Import your wallet" path. The original
    // managed-wallet code is kept (commented) in case we want it back later.
    return null;
    /* DISABLED auto-create:
    const { address, encryptedKey } = generateRealWallet();
    await db.insert(walletKeys).values({ userId, address, encryptedKey });
    await db.update(users).set({ walletAddress: address }).where(eq(users.id, userId));

    return {
      address,
      createdAt: new Date(),
      isImported: false,
    };
    */
  }),

  /**
   * Imports an external EVM wallet address for the user.
   * Removes any auto-generated wallet key — the user is now self-custodial.
   */
  importWallet: protectedProcedure
    .input(
      z.object({
        address: z
          .string()
          .refine(isValidEthAddress, { message: "Invalid Ethereum address" }),
      })
    )
    .mutation(async ({ ctx, input }) => {
      const db = await getDb();
      if (!db) throw new Error("Database unavailable");

      const userId = ctx.user.id;
      await db.update(users).set({ walletAddress: input.address }).where(eq(users.id, userId));
      await db.delete(walletKeys).where(eq(walletKeys.userId, userId));

      return { success: true, address: input.address };
    }),

  /**
   * Import a wallet by pasting a private key. Server derives the address,
   * encrypts the key with AES-256-GCM via KEY_ENCRYPTION_SECRET, stores in
   * wallet_keys. The user is now custodial-via-server with a key they brought.
   *
   * TESTNET ONLY: refuses to accept when FEATURE_MAINNET=true. Pasting a real
   * mainnet private key into a Telegram WebApp is unsafe — the key travels to
   * the backend in plaintext. Acceptable on testnet (no real funds at risk).
   * For mainnet flow, use the Privy embedded wallet or external-address-only
   * import.
   */
  importPrivateKey: protectedProcedure
    .input(
      z.object({
        // 0x-prefixed 64 hex chars, OR raw 64 hex chars (we normalize)
        privateKey: z.string().regex(/^(0x)?[a-fA-F0-9]{64}$/, "Private key must be 64 hex chars (with or without 0x prefix)"),
      })
    )
    .mutation(async ({ ctx, input }) => {
      assertRateLimit(ctx.user.id, "importPrivateKey", 3);
      if (ENV.featureMainnet) {
        throw new TRPCError({
          code: "FORBIDDEN",
          message: "Private-key import is disabled on mainnet. Use the embedded wallet flow (Privy) or import by address only.",
        });
      }

      // Normalize + derive address. ethers throws on invalid keys (zero, > curve order).
      const normalized = input.privateKey.startsWith("0x") ? input.privateKey : `0x${input.privateKey}`;
      let wallet: Wallet;
      try {
        wallet = new Wallet(normalized);
      } catch (err) {
        throw new TRPCError({
          code: "BAD_REQUEST",
          message: `Invalid private key: ${(err as Error).message}`,
        });
      }
      const address = wallet.address;

      const db = await getDb();
      if (!db) throw new TRPCError({ code: "SERVICE_UNAVAILABLE", message: "Database unavailable" });

      // Encrypt + store. encryptPrivateKey reads KEY_ENCRYPTION_SECRET by default
      // (prod-fatal in NODE_ENV=production if unset).
      const encryptedKey = encryptPrivateKey(normalized);
      const userId = ctx.user.id;

      // Replace any existing wallet_keys row for this user (single-wallet model)
      await db.delete(walletKeys).where(eq(walletKeys.userId, userId));
      await db.insert(walletKeys).values({ userId, address, encryptedKey, imported: true });

      // Provision a the venue API key + enable the managed wallet so the server can
      // sign this taker's payment leg in executeBurst. Best-effort + non-fatal:
      // if the venue is unreachable the wallet is still imported, just can't trade
      // until a key is provisioned. Testnet-only path (mainnet refused above).
      let dexApiKey: string | null = null;
      let dexApiSecretEnc: string | null = null;
      try {
        const client = getDexClient();
        const cfg = await client.getConfig();
        const timestamp = Math.floor(Date.now() / 1000);
        const sig = await wallet.signTypedData(
          cfg.eip712_domain,
          { ManageApiKey: [
            { name: "owner", type: "address" },
            { name: "action", type: "string" },
            { name: "timestamp", type: "uint256" },
          ] },
          { owner: address.toLowerCase(), action: "create", timestamp },
        );
        const res = await client.post<{ api_key?: string; api_secret?: string; secret?: string }>(
          "/api-keys",
          { owner_address: address.toLowerCase(), action: "create", timestamp, signature: sig, label: `import-${address.slice(0, 8)}` },
        );
        const k = res.api_key;
        const s = res.api_secret ?? res.secret;
        if (k && s) {
          dexApiKey = k;
          dexApiSecretEnc = encryptPrivateKey(s);
        }
      } catch (err) {
        console.warn(`[wallet] venue key provisioning failed for ${address}:`, err instanceof Error ? err.message : err);
      }

      await db.update(users)
        .set({ walletAddress: address, testnetFundStatus: "funding", ...(dexApiKey ? { dexApiKey, dexApiSecret: dexApiSecretEnc } : {}) })
        .where(eq(users.id, userId));

      // Enable managed wallet so the server can sign on this taker's behalf.
      // Upsert: replace any prior caps row for this user.
      await db.delete(managedWalletCaps).where(eq(managedWalletCaps.userId, userId));
      await db.insert(managedWalletCaps).values({
        userId,
        enabled: true,
        perTradeCapUsd: "100000",
        dailyVolumeCapUsd: "1000000",
        tokenAllowlist: "USDT,USDC,XSGD,JPYC,EURT",
        killed: false,
        enabledAt: new Date(),
      });

      // Kick auto-fund in the background (ETH + faucet claimTo). Fire-and-forget:
      // the import returns instantly; the client polls wallet.fundStatus. NEVER
      // awaited — a ~60–90s on-chain job must not block the request (see the
      // dashboard-freeze lesson). fundTestnetWallet never throws; it records
      // failure in users.testnetFundStatus.
      void fundTestnetWallet(userId, address);

      return { success: true, address, dexKeyProvisioned: !!dexApiKey };
    }),

  /**
   * Poll the testnet auto-fund job started on import.
   * Returns the status string (null | "funding" | "ready" | "error:<msg>").
   */
  fundStatus: protectedProcedure.query(async ({ ctx }) => {
    const db = await getDb();
    if (!db) return { status: null as string | null };
    const row = await db
      .select({ status: users.testnetFundStatus })
      .from(users)
      .where(eq(users.id, ctx.user.id))
      .limit(1);
    return { status: row[0]?.status ?? null };
  }),
});
